### ISSUE TITLE
Sinuous as peer dependency

### ISSUE THREAD

**Issue by luwes** [theSherwood/sinuous-style#1]
Very cool @theSherwood! Great addition for styling Sinuous components.

Some things that came to mind when I looked at the docs.

```js
let { shtml, ssvg, html, svg } = window.sinuousStyle(
  S.api,
  S.html,
  S.svg,
  S.root
);
```

This could be made easier by making Sinuous a peer dependency and then accessing sinuous directly in your module. It won't import the full Sinuous bundle if it's configured as a peer dependency. For Rollup the config would need an `external` option I believe.

Then in the user's code it be as easy as:

```js
import { shtml, ssvg } from 'sinuous/style';
```

or 

```js
let { shtml, ssvg } = window.sinuousStyle;
```

In the module's code you would just import whatever that is needed from the internal Sinuous api.

```js
import { html, svg, root, api } from 'sinuous';
```

**Comment by theSherwood** [comment]
> Very cool @theSherwood! Great addition for styling Sinuous components.

Thank you!

Okay. I don't completely understand. For ESM, I am using sinuous as a peer dependency and handling the config. Is that also possible for an iife CDN?

**Comment by luwes** [comment]
yes, Rollup will just make sure the Sinuous imports are accessible via the `window.sinuous` property. eg `window.sinuous.api`, `window.sinuous.html`, etc.

it's a bit like how jQuery plugins work, they rely on window.jQuery being available in the window. so in users code they don't have to manually add any jQuery methods to the plugins. the plugins just rightly assume jQuery will be there.

**Comment by theSherwood** [comment]
Great! I was unaware of that. I'll probably get this pulled together tomorrow, as well as apply it to [sinuous-context](https://github.com/theSherwood/sinuous-context) and [sinuous-bind](https://github.com/theSherwood/sinuous-bind) if I get time. There are some improvements that can be made to the config of sinuous-bind especially.

**Comment by theSherwood** [comment]
These changes have been made. Thanks for making me aware that this was possible!
